version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: daily_dashboard_dev
    restart: always
    environment:
      POSTGRES_USER: daily_dashboard
      POSTGRES_PASSWORD: 123456a@
      POSTGRES_DB: daily_dashboard_dev
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5433:5432
